# Generated by Django 5.0.4 on 2024-04-24 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_name_alter_book_book_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 9, 14, 8, 244617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='issue_date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
    ]
