# Generated by Django 5.0.4 on 2024-04-24 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 14, 29, 47, 26442, tzinfo=datetime.timezone.utc)),
        ),
    ]
